# Generated by Django 2.1.3 on 2019-01-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_detalle', models.CharField(max_length=500)),
                ('precio', models.CharField(max_length=500)),
                ('fecha', models.CharField(max_length=500)),
            ],
        ),
    ]
